
Router = Package["iron:router"].Router,
RouteController = Package["iron:router"].RouteController,
GoogleMaps = Package["dburles:google-maps"].GoogleMaps,
moment = Package["momentjs:moment"].moment,
ServiceConfiguration = Package["service-configuration"].ServiceConfiguration,
Slingshot = Package["edgee:slingshot"].Slingshot,
ReactiveVar = Package["reactive-var"].ReactiveVar,
Facebook = Package.facebook.Facebook,
Google = Package.google.Google,
OAuth = Package.oauth.OAuth,
Oauth = Package.oauth.Oauth,
MeteorCamera = Package["mdg:camera"].MeteorCamera,
AWS = Package["eluck:aws-sdk"].AWS,
HTTP = Package.http.HTTP,
xml2js = Package["peerlibrary:xml2js"].xml2js,
_cloudinary = Package["lepozepo:cloudinary"]._cloudinary,
C = Package["lepozepo:cloudinary"].C,
Kadira = Package["meteorhacks:kadira"].Kadira,
Spiderable = Package.spiderable.Spiderable,
GAnalytics = Package["datariot:ganalytics"].GAnalytics,
FacebookCollections = Package["maxkferg:facebook-collections"].FacebookCollections,
Autolinker = Package["konecty:autolinker"].Autolinker,
UserStatus = Package["mizzao:user-status"].UserStatus,
Meteor = Package.meteor.Meteor,
WebApp = Package.webapp.WebApp,
Log = Package.logging.Log,
Tracker = Package.deps.Tracker,
Deps = Package.deps.Deps,
Session = Package.session.Session,
DDP = Package.livedata.DDP,
Mongo = Package.mongo.Mongo,
Blaze = Package.ui.Blaze,
UI = Package.ui.UI,
Handlebars = Package.ui.Handlebars,
Spacebars = Package.spacebars.Spacebars,
Template = Package.templating.Template,
check = Package.check.check,
Match = Package.check.Match,
_ = Package.underscore._,
$ = Package.jquery.$,
jQuery = Package.jquery.jQuery,
Random = Package.random.Random,
EJSON = Package.ejson.EJSON,
LaunchScreen = Package["launch-screen"].LaunchScreen,
Accounts = Package["accounts-base"].Accounts,
Iron = Package["iron:core"].Iron,
Async = Package["meteorhacks:async"].Async,
HTML = Package.htmljs.HTML;







